app: favonius-server
service: favonius-server-api
useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  profile: serverless-admin
  runtime: nodejs12.x
  region: us-west-2
  lambdaHashingVersion: 20201221

functions:
  main:
    handler: src/serverless.handler
    events:
      - http:
          path: graphql
          method: POST
          cors: true
      - http:
          path: graphql
          method: GET
          cors: true
      - http:
          path: playground
          method: ANY
          cors: true
          timeout: 300 # optional, in seconds, default is 6
