app: favonius-server
service: favonius-server-api
useDotenv: true

package:
  patterns:
    - '!dist/**'
    - '!src/seeds/**'

plugins:
  - serverless-plugin-typescript
  # - serverless-plugin-optimize
  - serverless-offline

# custom:
#   serverless-offline:
#     allowCache: true # ~100ms

provider:
  name: aws
  profile: serverless-admin
  runtime: nodejs12.x
  region: us-west-2
  lambdaHashingVersion: 20201221

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          path: graphql
          method: POST
          cors: true
          integration: LAMBDA
      - http:
          path: graphql
          method: GET
          cors: true
          integration: LAMBDA
      - http:
          path: playground
          method: ANY
          cors: true
          integration: LAMBDA
